learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    url(r'^medative/$', views.medative, name='medative'),
    url(r'^other/$', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text": "Hello Univers", "number": 240}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def medative(request):
    return render(request, 'basic_app/medative.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <ul class="navbar-nav">
          <li><a class="navbar-brand" href="{% url "index" %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url "admin:index" %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url "basic_app:other" %}">OTHER</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
        <!-- Anything outside of this will be inherited if Extends! -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to Index page!</h1>
    <a href="{% url 'basic_app:other' %}">Go to other page</a>
  </br>
    {{ text|cut:"Univers" }}
  </br>
    {{ number|add:60 }}
  {% endblock %}

learning_templates/templates/basic_app/medative.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to medative page, Relative URL Templates!</h1>
    <a href="{% url 'index' %}">Go to the index page</a>
    </br>
    <a href="{% url 'admin:index' %}">Admin page</a>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <h1>Welcome to other page!</h1>
    <a href="{% url 'basic_app:medative' %}">Link to Medative page</a>

  {% endblock %}